name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} -r . ubuntu@44.223.25.245:/home/ubuntu/my-medusa-store
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@44.223.25.245 "cd /home/ubuntu/my-medusa-store && npm install"

    - name: Start Medusa
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@44.223.25.245 "cd /home/ubuntu/my-medusa-store && npm run start"
